server:
  port: 8761
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    hostname: localhost
  client:
    registerWithEureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    fetch-registry: false
  server:
    enable-self-preservation: false
spring:
  application:
    name: eureka